server.port=8080
ducklake.postgres.host=${POSTGRES_HOST:localhost}
ducklake.postgres.port=${POSTGRES_PORT:5432}
ducklake.postgres.db=${POSTGRES_DB:ducklake}
ducklake.postgres.user=${POSTGRES_USER:duck}
ducklake.postgres.password=${POSTGRES_PASSWORD:postgres}
ducklake.s3.endpoint=${S3_ENDPOINT:}
ducklake.s3.keyid=${S3_KEY_ID:minioadmin}
ducklake.s3.secret=${S3_SECRET:minioadmin}
ducklake.s3.bucket=${S3_BUCKET:ducklake}
ducklake.s3.region=${S3_REGION:local}
ducklake.api.key=${API_KEY:change-me}
